steps:
  - name: 'python:3.9'
    entrypoint: 'python'
    args:
      - '-m'
      - 'venv'
      - 'fried_venv'
  - name: 'python:3.9'
    args:
      - 'source'
      - 'fried_venv/bin/activate'
  - name: 'python:3.9'
    entrypoint: 'python'
    args:
      - '-m'
      - 'pip'
      - 'install'
      - '-r'
      - 'requirements.txt'
  - name: 'python:3.9'
    entrypoint: 'python'
    args:
      - 'main.py'

