steps:
  - name: 'python:3.9'
    entrypoint: 'python3'
    args: ['-m', 'pip', 'install', 'virtualenv']
  - name: 'python:3.9'
    entrypoint: 'python3'
    args: ['-m', 'virtualenv', 'venv']
  - name: 'python:3.9'
    args: ['venv/bin/pip', 'install', '-r', 'requirements.txt']
  - name: 'python:3.9'
    args: ['venv/bin/python', 'main.py']
