steps:
  - name: 'python:3.9'
    entrypoint: 'python3'
    args:
      - '-m'
      - 'venv'
      - 'fried-venv'
  - name: 'bash'
    args:
      - 'source'
      - 'fried-venv/bin/activate'
  - name: 'python:3.9'
    entrypoint: 'python3'
    args:
      - '-m'
      - 'pip'
      - 'install'
      - '-r'
      - 'requirements.txt'
  - name: 'python:3.9'
    entrypoint: 'python3'
    args:
      - 'main.py'
