steps:
  # Install pip and create virtual environment (venv)
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update
        apt-get install -y python3-venv
        python3 -m venv env
        source env/bin/activate
        pip install -U pip
  # Install required libraries
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source env/bin/activate
        pip install -r requirements.txt
  # Copy files to Compute Engine instance
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute scp --recurse . my-instance:~
  # SSH into Compute Engine instance and run the application
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh instance-1 --command='source env/bin/activate && python3 main.py'
