steps:
  - name: 'python:3.9'
    entrypoint: 'python'
    args:
      - '-m'
      - 'pip'
      - 'install'
      - '--user'
      - 'pipenv'
  - name: 'python:3.9'
    entrypoint: 'python'
    args:
        - '-m'
        - 'pipenv'
        - 'install'
        - '--deploy'
        - '--system'
        - '--dev'
        - '--ignore-pipfile'
  - name: 'python:3.9'
    entrypoint: 'python'
    args:
      - '-m'
      - 'pip'
      - 'install'
      - '-r'
      - 'requirements.txt'
  - name: 'python:3.9'
    entrypoint: 'python'
    args:
      - 'main.py'


