steps:
  - name: 'python:3.9'
    entrypoint: 'python3'
    args:
      - '-m'
      - 'pip'
      - 'install'
      - '--upgrade'
      - 'pip'
  - name: 'python:3.9'
    entrypoint: 'python3'
    args:
      - '-m'
      - 'virtualenv'
      - 'venv'
  - name: 'python:3.9'
    entrypoint: 'python3'
    args:
      - '-m'
      - 'venv'
      - 'venv'
  - name: 'python:3.9'
    entrypoint: 'python3'
    args:
      - 'pip'
      - 'install'
      - '-r'
      - 'requirements.txt'
  - name: 'python:3.9'
    entrypoint: 'python3'
    args:
      - 'main.py'
