steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'hello', '--image', 'gcr.io/$PROJECT_ID/hello', '--platform', 'managed', '--region', 'us-central1']

