steps:
  # Install pip
  - name: 'python:3.9'
    entrypoint: 'bash'
    args: ['-c', 'apt-get update && apt-get -y install python3-pip']
  # Create a virtual environment (venv)
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python3 -m venv env
        source env/bin/activate
  # Install required libraries from requirements.txt
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source env/bin/activate
        python3 -m pip install -r requirements.txt
  # Run the main file
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source env/bin/activate
        python3 main.py
